### ISSUE TITLE
injective missing on sushi-analytics

### ISSUE THREAD

**Issue by shane-moore** [DefiLlama/sushi-analytics#11]
## Situation
- I run `npm run tvl` > `injective-orderbook` on `defillama-adapters` repo, and see this error:
<img width="890" alt="image" src="https://github.com/DefiLlama/sushi-analytics/assets/41407272/27ffc147-3390-4eb9-9744-4505ab7fa337">
- After a quick investigation, I see that there is no data for injective-orderbook at https://sushi-analytics.onrender.com/?chain=injective&project=injective-orderbook, so I assume there is some issue with the cron job to populate the endpoint. Can you please investigate? 

cc @g1nt0ki

**Comment by g1nt0ki** [comment]
hi @shane-moore thanks for notifying us, fixed the issue now
