### ISSUE TITLE
injective missing on sushi-analytics

### ISSUE THREAD

**Issue by shane-moore** [DefiLlama/sushi-analytics#12]
## Situation
Hi @g1nt0ki,  I noticed the same error as reported in issue https://github.com/DefiLlama/sushi-analytics/issues/11 has returned

Perhaps it would be resolved by upping the `sdk-ts` in the `package.json` to a more current version?
Latest:
https://www.npmjs.com/package/@injectivelabs/sdk-ts
https://www.npmjs.com/package/@injectivelabs/networks

**Comment by g1nt0ki** [comment]
thanks,  this is fixed now
